---
- name: Include Tailscale role
  block:
    - name: Set Tailscale variables
      ansible.builtin.set_fact:
        tailscale_authkey: "{{ tailscale_authkey }}"
        tailscale_args: "--ssh"

    - name: Install and configure Tailscale
      ansible.builtin.include_role:
        name: artis3n.tailscale.machine